import { ArrowRight, Check } from "lucide-react";
import Link from "next/link";
import PageHero from "@/components/Site/PageHero";
import { services } from "@/lib/content";

export const metadata = { title: "Services", description: "Video editing, social media management, digital development, creative strategy and brand design." };
const groups = [
  { title: "Create", text: "Editing, product creative and design turn source material into polished assets." },
  { title: "Connect", text: "Social management and strategy keep those assets aligned with an audience and purpose." },
  { title: "Convert", text: "Web and app experiences give attention a useful next destination." },
];

export default function ServicesPage() {
  return <><PageHero eyebrow="Services" title="Creative services built around your business." description="From the first content idea to the final published asset, SocialEdge brings strategy, production and digital execution into one focused partnership." />
    <section className="mx-auto max-w-6xl px-4 py-20"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">A connected model</p><h2 className="section-title">Choose one capability or connect the full journey.</h2><p className="mt-5 leading-7 text-slate-600">A project can begin with a specific need—an edit, a content plan, a product campaign or a website. When the work crosses disciplines, the same direction can carry through each stage.</p></div><div className="grid gap-4 sm:grid-cols-3">{groups.map((group, index) => <article key={group.title} className="rounded-2xl border border-emerald-950/10 bg-white p-6"><span className="text-sm font-bold text-emerald-700">0{index + 1}</span><h3 className="mt-4 text-xl font-semibold">{group.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{group.text}</p></article>)}</div></div></section>
    <section className="border-y border-emerald-950/10 bg-white/65 px-4 py-20"><div className="mx-auto max-w-6xl"><p className="eyebrow">Capabilities</p><h2 className="section-title">Six practical ways to move the brand forward.</h2><div className="mt-10 grid gap-6 md:grid-cols-2">{services.map((service, index) => <article key={service.title} className="rounded-3xl border border-emerald-950/10 bg-white p-8"><span className="text-sm font-bold text-emerald-700">0{index + 1}</span><h3 className="mt-4 font-display text-3xl font-semibold">{service.title}</h3><p className="mt-4 leading-7 text-slate-600">{service.description}</p><ul className="mt-6 grid gap-3">{service.details.map((detail) => <li key={detail} className="flex items-center gap-3 text-sm"><Check className="h-4 w-4 text-emerald-700" />{detail}</li>)}</ul><Link href={`/services/${service.slug}`} className="mt-7 inline-flex items-center gap-2 rounded-full border border-site-primary/20 px-5 py-2.5 text-sm font-semibold text-site-primary transition hover:bg-site-primary hover:text-white">Explore this service <ArrowRight className="h-4 w-4"/></Link></article>)}</div></div></section>
    <section className="mx-auto max-w-6xl px-4 py-20"><div className="grid gap-8 rounded-[2rem] bg-site-primary p-8 text-white sm:p-12 lg:grid-cols-[1fr_1fr]"><div><p className="eyebrow !text-site-btnPrimary">Where should you start?</p><h2 className="mt-3 font-display text-4xl font-semibold">Start with the clearest current challenge.</h2><p className="mt-5 leading-7 text-white/60">If you have footage but need polish, begin with editing. If publishing feels disconnected, begin with strategy or management. If attention has nowhere useful to go, begin with the digital experience.</p></div><div className="grid gap-3">{["What are you trying to communicate?", "What source material already exists?", "Where will the audience see it?", "What should happen after they engage?"].map((item) => <div key={item} className="rounded-xl border border-white/10 bg-white/5 p-4 font-medium">{item}</div>)}<Link href="/pricing#booking" className="mt-2 inline-flex w-fit rounded-full bg-site-btnPrimary px-6 py-3 font-semibold text-site-primary">Share your project</Link></div></div></section>
  </>;
}
