"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
export default function AdminLogin(){
 const router=useRouter(); const [setup,setSetup]=useState<boolean|null>(null); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
 useEffect(()=>{fetch('/api/auth/status').then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error);setSetup(x.needsSetup)}).catch(e=>setError(e.message))},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError('');const values=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch(setup?'/api/auth/setup':'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)});const x=await r.json().catch(()=>({}));if(r.ok){router.push('/admin');router.refresh()}else{setError(x.error??'Unable to continue.');setLoading(false)}}
 return <main className="grid min-h-screen place-items-center bg-slate-100 px-4 py-12"><div className="w-full max-w-md rounded-3xl border border-slate-200 bg-white p-8 shadow-xl"><div className="mx-auto w-fit rounded-2xl bg-site-primary px-6 py-2"><Image src="/identity/SocialEdge.png" width={180} height={60} alt="SocialEdge Creative" className="object-contain"/></div><div className="mt-7 text-center"><p className="text-xs font-bold uppercase tracking-[.25em] text-emerald-700">Private workspace</p><h1 className="mt-3 text-3xl font-semibold text-slate-900">{setup===true?'Create primary admin':setup===false?'Welcome back':'Checking setup…'}</h1><p className="mt-2 text-sm text-slate-500">{setup?'This one-time form will secure the CRM.':'Sign in to manage project inquiries.'}</p></div>{setup!==null&&<form onSubmit={submit} className="mt-8 grid gap-5"><label className="grid gap-2 text-sm font-semibold">Email<input name="email" type="email" required autoComplete="email" className="rounded-xl border border-slate-200 px-4 py-3"/></label><label className="grid gap-2 text-sm font-semibold">Password<input name="password" type="password" minLength={10} required autoComplete={setup?'new-password':'current-password'} className="rounded-xl border border-slate-200 px-4 py-3"/></label><button disabled={loading} className="rounded-xl bg-site-primary px-5 py-3 font-semibold text-white disabled:opacity-50">{loading?'Please wait…':setup?'Create admin account':'Sign in'}</button></form>}{error&&<p role="alert" className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<a href="/" className="mt-6 block text-center text-sm text-slate-500">← Return to website</a></div></main>
}

