import Link from "next/link";
import { ArrowRight, Check, Layers, MonitorSmartphone, Palette, ShoppingBag, Sparkles, Video } from "lucide-react";
import ShortsGrid from "@/components/Site/ShortsGrid";
import AnimatedShortsStack from "@/components/Site/AnimatedShortsStack";
import CreativeUniverse from "@/components/Site/CreativeUniverse";
import { platformFormats, qualityCriteria, services, siteFaqs, useCases } from "@/lib/content";

const icons = [Video, Sparkles, ShoppingBag, MonitorSmartphone, Layers, Palette];
const systemStages = [
  { number: "01", title: "Strategy", text: "Define the audience, message, channel and job each asset needs to do." },
  { number: "02", title: "Production", text: "Turn source ideas and footage into purposeful edits, graphics and digital experiences." },
  { number: "03", title: "Distribution", text: "Prepare framing, pacing and formats for the platforms where people will discover the work." },
  { number: "04", title: "Destination", text: "Connect attention to a clear website, product or inquiry experience." },
];

export default function Home() {
  return <>
    <section className="relative overflow-hidden bg-site-primary px-4 pb-20 pt-32 text-white sm:pt-40">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_15%,rgba(141,253,186,.16),transparent_32%)]" />
      <div className="relative mx-auto grid max-w-6xl items-center gap-12 lg:grid-cols-[1.05fr_.95fr]">
        <div><p className="text-xs font-semibold uppercase tracking-[.32em] text-site-btnPrimary">SocialEdge Creatives</p><h1 className="mt-5 font-display text-5xl font-semibold leading-[1.05] sm:text-6xl lg:text-7xl">Content that gets your brand noticed.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/70">We transform raw ideas and footage into high-impact social content, polished video and digital experiences built to help businesses grow.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/pricing#booking" className="rounded-full bg-site-btnPrimary px-7 py-3.5 text-center font-semibold text-site-primary">Start a project</Link><Link href="/our-work" className="rounded-full border border-white/30 px-7 py-3.5 text-center font-semibold">Watch our work</Link></div></div>
        <div className="relative"><AnimatedShortsStack compact /></div>
      </div>
    </section>

    <section className="mx-auto max-w-6xl px-4 py-20"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">What is SocialEdge?</p><h2 className="section-title">A creative partner for the way people watch, shop and connect today.</h2></div><div className="space-y-5 text-lg leading-8 text-slate-600"><p>SocialEdge is a social media management and video editing company that turns raw content into a powerful tool for business growth.</p><p>We create trend-aware work for Instagram, TikTok and YouTube, helping brands strengthen their online presence, engage their audience and turn attention into measurable opportunities.</p></div></div></section>

    <section className="border-y border-emerald-950/10 bg-white/70 px-4 py-20"><div className="mx-auto max-w-6xl"><div className="grid gap-12 lg:grid-cols-[.9fr_1.1fr]"><div><p className="eyebrow">Why systems matter</p><h2 className="section-title">More content is not the same as more clarity.</h2><p className="mt-5 leading-7 text-slate-600">When strategy, editing, design and distribution are treated as separate tasks, the brand can feel fragmented. A connected content system gives every asset a role, a shared visual language and a clear destination.</p><p className="mt-4 leading-7 text-slate-600">That means one strong idea can travel further without losing what makes it recognizable.</p></div><div className="grid gap-4 sm:grid-cols-2">{systemStages.map((stage) => <article key={stage.title} className="rounded-2xl border border-emerald-950/10 bg-white p-6"><span className="text-sm font-bold text-emerald-700">{stage.number}</span><h3 className="mt-3 text-xl font-semibold">{stage.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{stage.text}</p></article>)}</div></div></div></section>

    <section className="overflow-hidden bg-site-primary px-4 py-20 text-white"><div className="mx-auto grid max-w-6xl items-center gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow !text-site-btnPrimary">Your content ecosystem</p><h2 className="mt-3 font-display text-4xl font-semibold leading-tight sm:text-5xl">One creative core. Many useful expressions.</h2><p className="mt-5 leading-7 text-white/65">The strongest digital presence connects what you say, how it looks, where it appears and what happens after someone pays attention.</p><div className="mt-8 grid gap-3">{systemStages.map((stage) => <div key={stage.title} className="flex gap-4 rounded-xl border border-white/10 bg-white/5 p-4"><span className="font-bold text-site-btnPrimary">{stage.number}</span><div><h3 className="font-semibold">{stage.title}</h3><p className="mt-1 text-sm text-white/55">{stage.text}</p></div></div>)}</div></div><CreativeUniverse /></div></section>

    <section className="overflow-hidden border-b border-emerald-950/10 bg-white py-6"><div className="flex min-w-max animate-[marquee_28s_linear_infinite] gap-3 px-4 motion-reduce:animate-none">{[...platformFormats, ...platformFormats].map((format, index) => <span key={`${format}-${index}`} className="rounded-full border border-emerald-950/10 bg-site-primary/5 px-5 py-2.5 text-sm font-semibold text-site-primary">{format}</span>)}</div></section>

    <section className="border-b border-emerald-950/10 bg-white/65 px-4 py-20"><div className="mx-auto max-w-6xl"><p className="eyebrow">What we offer</p><div className="mt-3 flex flex-col justify-between gap-4 md:flex-row md:items-end"><h2 className="section-title max-w-2xl">One connected team across content, brand and digital.</h2><Link href="/services" className="font-semibold text-site-primary">Explore every service <ArrowRight className="inline h-4 w-4" /></Link></div><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{services.map((service, index) => { const Icon = icons[index]; return <Link href={`/services/${service.slug}`} key={service.title} className="group rounded-3xl border border-emerald-950/10 bg-white p-7 transition hover:-translate-y-1 hover:shadow-soft"><Icon className="h-7 w-7 text-emerald-700" /><h3 className="mt-6 text-xl font-semibold">{service.title}</h3><p className="mt-3 leading-7 text-slate-600">{service.description}</p><span className="mt-5 inline-block text-sm font-semibold text-emerald-800">Learn more →</span></Link>; })}</div></div></section>

    <section className="mx-auto max-w-6xl px-4 py-20"><div className="mb-10 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">Selected work</p><h2 className="section-title">Editing made to stop the scroll.</h2></div><Link href="/our-work" className="rounded-full border border-site-primary/20 px-5 py-2.5 font-semibold">View all 16 edits</Link></div><ShortsGrid limit={4} /></section>

    <section className="bg-site-primary px-4 py-20 text-white"><div className="mx-auto max-w-6xl"><p className="eyebrow !text-site-btnPrimary">Built for different starting points</p><h2 className="mt-3 max-w-3xl font-display text-4xl font-semibold">Creative support shaped around the kind of work you need.</h2><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{useCases.map((item) => <article key={item.title} className="rounded-2xl border border-white/10 bg-white/5 p-6"><h3 className="text-xl font-semibold">{item.title}</h3><p className="mt-3 text-sm leading-6 text-white/60">{item.description}</p></article>)}</div></div></section>

    <section className="mx-auto max-w-6xl px-4 py-20"><div className="grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow">One idea, more value</p><h2 className="section-title">Turn source material into a connected family of assets.</h2><p className="mt-5 leading-7 text-slate-600">A useful recording, product demonstration or campaign thought does not have to live in one format. Planning the system early helps the core message remain consistent as it becomes different pieces of content.</p></div><div className="grid gap-3">{["Raw idea, interview or product story", "Core narrative and visual direction", "Short edits, long-form cuts and promotional assets", "Platform-ready delivery and digital destination"].map((item, index) => <div key={item} className="flex items-center gap-5 rounded-2xl border border-emerald-950/10 bg-white p-5"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-site-btnPrimary font-bold">{index + 1}</span><p className="font-semibold">{item}</p></div>)}</div></div></section>

    <section className="border-y border-emerald-950/10 bg-white/70 px-4 py-20"><div className="mx-auto max-w-6xl"><p className="eyebrow">What we look for</p><h2 className="section-title">The details that make content easier to watch and remember.</h2><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{qualityCriteria.map((item) => <article key={item.title} className="rounded-2xl border border-emerald-950/10 bg-white p-6"><Check className="h-5 w-5 text-emerald-700"/><h3 className="mt-4 text-lg font-semibold">{item.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{item.description}</p></article>)}</div></div></section>

    <section className="mx-auto max-w-6xl px-4 py-20"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Questions</p><h2 className="section-title">A clearer way to start.</h2><p className="mt-5 leading-7 text-slate-600">The project form helps us understand the service, material and direction before shaping the next conversation.</p></div><div className="grid gap-3">{siteFaqs.map((item) => <details key={item.question} className="group rounded-2xl border border-emerald-950/10 bg-white p-5"><summary className="cursor-pointer list-none font-semibold">{item.question}<span className="float-right text-emerald-700 group-open:rotate-45">+</span></summary><p className="mt-4 leading-7 text-slate-600">{item.answer}</p></details>)}</div></div></section>

    <section className="mx-auto max-w-6xl px-4 pb-24"><div className="flex flex-col items-start justify-between gap-7 rounded-[2rem] bg-site-primary p-8 text-white sm:p-12 lg:flex-row lg:items-center"><div><p className="eyebrow !text-site-btnPrimary">Ready to connect the pieces?</p><h2 className="mt-3 max-w-2xl font-display text-4xl font-semibold">Bring the idea, footage or challenge. We’ll help shape the creative path.</h2></div><Link href="/pricing#booking" className="shrink-0 rounded-full bg-site-btnPrimary px-7 py-3.5 font-semibold text-site-primary">Start a project</Link></div></section>
  </>;
}
