import { Check } from "lucide-react";
import PageHero from "@/components/Site/PageHero";

const values = [{title:"Trend-aware, not trend-dependent",text:"We understand digital formats while keeping your brand recognizable and useful beyond a single moment."},{title:"Creative with a business purpose",text:"Every editing, design and content decision starts with the audience and the action you want them to take."},{title:"One connected creative partner",text:"Strategy, production, social content and digital delivery stay aligned instead of passing between disconnected vendors."},{title:"Built around your brand",text:"We learn your voice and adapt the process to your goals rather than forcing every client into the same formula."}];
const standards = ["The opening earns attention without misleading the audience", "The message remains clear even when the format is fast", "Captions and graphics support rather than crowd the story", "Visual choices remain consistent with the brand", "The final asset fits its intended screen and platform", "Feedback is applied without losing the purpose of the work"];
export const metadata = { title: "Why Us", description: "Why businesses choose SocialEdge as their creative and social media partner." };

export default function WhyPage(){return <><PageHero eyebrow="Why SocialEdge" title="A professional partner who understands digital attention." description="We combine creative craft with an understanding of social platforms, helping businesses show up consistently and turn content into a practical growth tool."/>
  <section className="mx-auto max-w-6xl px-4 py-20"><p className="eyebrow">Our principles</p><h2 className="section-title max-w-3xl">Creative work should feel current, coherent and useful to the business.</h2><div className="mt-10 grid gap-6 md:grid-cols-2">{values.map((value,index)=><article key={value.title} className="rounded-3xl border border-emerald-950/10 bg-white p-8"><span className="text-sm font-bold text-emerald-700">0{index+1}</span><h3 className="mt-4 text-2xl font-semibold">{value.title}</h3><p className="mt-3 leading-7 text-slate-600">{value.text}</p></article>)}</div></section>
  <section className="bg-site-primary px-4 py-20 text-white"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow !text-site-btnPrimary">Our review standard</p><h2 className="mt-3 font-display text-4xl font-semibold">Details are reviewed in context, not isolation.</h2><p className="mt-5 leading-7 text-white/60">A polished transition cannot rescue an unclear message. We look at the idea, audience, pacing, brand and destination together.</p></div><div className="grid gap-3 sm:grid-cols-2">{standards.map((item)=><div key={item} className="flex gap-3 rounded-2xl border border-white/10 bg-white/5 p-4 text-sm leading-6 text-white/75"><Check className="mt-0.5 h-4 w-4 shrink-0 text-site-btnPrimary"/>{item}</div>)}</div></div></section>
  <section className="mx-auto max-w-6xl px-4 py-20"><div className="grid gap-10 lg:grid-cols-2"><div><p className="eyebrow">Working together</p><h2 className="section-title">A visible path from context to delivery.</h2><p className="mt-5 leading-7 text-slate-600">The collaboration starts by understanding what exists, what needs to change and what the finished work must accomplish. Review points stay connected to that original purpose.</p></div><div className="grid gap-4">{["Share the objective, audience and available material", "Align on direction, formats and useful references", "Review the work against message and brand", "Prepare approved assets for their intended channels"].map((item,index)=><div key={item} className="flex gap-4 rounded-2xl border border-emerald-950/10 bg-white p-5"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-site-btnPrimary font-bold">{index+1}</span><p className="pt-1.5 font-medium">{item}</p></div>)}</div></div></section>
  </>}
