import Link from "next/link";
import PageHero from "@/components/Site/PageHero";

const needs=["Ongoing social media content","A repeatable video editing pipeline","E-commerce promotional creative","Web and app creative support","Campaign strategy and brand design","Flexible output across multiple formats"];
const stages=[{title:"Map the demand",text:"Identify channels, recurring formats, source material and the people involved in review."},{title:"Set the system",text:"Create a practical rhythm for briefs, priorities, feedback and delivery."},{title:"Build consistently",text:"Keep creative decisions connected across video, social, design and digital work."},{title:"Review and adapt",text:"Use what the team learns to clarify the next cycle of content."}];
export const metadata={title:"Enterprise",description:"Flexible creative support for organizations with ongoing content needs."};

export default function EnterprisePage(){return <><PageHero eyebrow="For Teams" title="Creative support for larger, ongoing content needs." description="SocialEdge can bring editing, social content, design and digital production together around an organization’s priorities without making unsupported one-size-fits-all promises."/>
  <section className="mx-auto max-w-6xl px-4 py-20"><div className="grid gap-10 lg:grid-cols-2"><div><p className="eyebrow">Flexible partnership</p><h2 className="section-title">A broader creative capability, shaped around the brief.</h2><p className="mt-5 leading-7 text-slate-600">For organizations that need recurring work or support across several channels, we begin by understanding volume, formats, stakeholders and timelines. From there, we propose a practical working model.</p></div><div className="grid gap-3">{needs.map((item)=><div key={item} className="rounded-2xl border border-emerald-950/10 bg-white px-5 py-4 font-medium">{item}</div>)}</div></div></section>
  <section className="border-y border-emerald-950/10 bg-white/70 px-4 py-20"><div className="mx-auto max-w-6xl"><p className="eyebrow">A content operating model</p><h2 className="section-title max-w-3xl">Structure the flow without making the creative feel mechanical.</h2><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{stages.map((stage,index)=><article key={stage.title} className="rounded-2xl border border-emerald-950/10 bg-white p-6"><span className="text-sm font-bold text-emerald-700">0{index+1}</span><h3 className="mt-4 text-xl font-semibold">{stage.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{stage.text}</p></article>)}</div></div></section>
  <section className="mx-auto max-w-6xl px-4 py-20"><div className="grid gap-10 rounded-[2rem] bg-site-primary p-8 text-white sm:p-12 lg:grid-cols-2"><div><p className="eyebrow !text-site-btnPrimary">Planning the engagement</p><h2 className="mt-3 font-display text-4xl font-semibold">Begin with the real workflow, not a generic package.</h2><p className="mt-5 leading-7 text-white/60">The right structure depends on what your team already handles, where capacity is missing and how work is approved.</p></div><div className="grid gap-3">{["Which channels and formats are priorities?", "What volume and source material should be considered?", "Who supplies context and who approves the work?", "Which services need to work together?"].map((item)=><div key={item} className="rounded-xl border border-white/10 bg-white/5 p-4 font-medium">{item}</div>)}<Link href="/pricing#booking" className="mt-2 inline-flex w-fit rounded-full bg-site-btnPrimary px-6 py-3 font-semibold text-site-primary">Describe your requirements</Link></div></div></section>
  </>}
